name: curso_flutter_unipampa
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.0.5
  http: ^1.1.0

  #Geração da estrutura da arquitetura limpa
  ft_cli: ^0.1.8+9

  # Gerenciamento de estado
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5

  # Injeção de dependência e rotas
  flutter_modular: ^5.0.3
  modular_core: ^2.0.3+1

  # Requisições http
  dio: ^5.3.0



dev_dependencies:
  mobx_codegen: ^2.3.0
  modular_test: ^2.0.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:

  uses-material-design: true
